version: 2
references:
  container_config: &container_config
    docker:
      - image: electronuserland/electron-builder:latest
        environment:
          TARGET_ARCH: x64
    working_directory: ~/neon-wallet

  workspace_root: &workspace_root
    ~/neon-wallet
    
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: neon-wallet-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn dist
      - save_cache:
          key: neon-wallet-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache
            - ./node_modules
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist/*
  test:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: neon-wallet-{{ checksum "yarn.lock" }}
      - run: yarn test
    store_artifacts:
      - path: artifacts/
      - destination: yarnpkg

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build